# Файл: .github/workflows/sync.yml
# Эта версия правильная, ее можно не трогать, если она уже такая.

name: 'Авто-синхронизация плейлиста'

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Получение кода репозитория'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Установка Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 'Установка зависимостей'
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 'Запуск скрипта обновления плейлиста'
        run: python update_playlist.py

      - name: 'Сохранение изменений в репозиторий'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖✅ Авто-обновление: плейлист синхронизирован'
          # Важно: имя файла должно совпадать с вашим
          file_pattern: 'IPTV_SHARED.m3u' 
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'
