name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */2 * * *'  # Каждые 2 часа
  workflow_dispatch:  # Ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        
    - name: Force sync with remote (resolve divergence)
      run: |
        echo "Текущее состояние:"
        git status
        echo ""
        echo "Принудительная синхронизация с origin/main..."
        git fetch origin
        git checkout main
        git reset --hard origin/main
        echo "Синхронизация завершена"
        
    - name: Run update script
      run: |
        echo "Запуск скрипта обновления..."
        python update_playlist.py
        
    - name: Check for changes and commit
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Обнаружены изменения, делаем коммит..."
          git add IPTV_SHARED.m3u
          git commit -m "🤖✅ Авто-обновление: плейлист синхронизирован $(date '+%Y-%m-%d %H:%M:%S UTC')"
          
          echo "Попытка push..."
          if git push origin main; then
            echo "✅ Push успешно выполнен"
          else
            echo "❌ Обычный push не удался, пробуем force push..."
            git push origin main --force
            echo "✅ Force push выполнен"
          fi
        else
          echo "Изменений не обнаружено"
        fi
