# Имя файла: .github/workflows/sync.yml
# ВЕРСИЯ 2.0 - С ИСПРАВЛЕНИЕМ ОШИБКИ [REJECTED]

name: 'Авто-синхронизация плейлиста'

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Шаг 1: Скачиваем код вашего репозитория.
      # Мы добавляем `fetch-depth: 0`, чтобы получить полную историю для корректного слияния.
      - name: 'Получение кода репозитория'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # <-- ВАЖНОЕ ДОБАВЛЕНИЕ

      # Шаг 2: Устанавливаем Python
      - name: 'Установка Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 3: Устанавливаем зависимости
      - name: 'Установка зависимостей'
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Шаг 4: Запускаем наш основной скрипт обновления
      - name: 'Запуск скрипта обновления плейлиста'
        run: python update_playlist.py

      # Шаг 5: Сохраняем изменения (делаем коммит)
      # Этот экшен умный и сам справится с расхождениями, если у него есть полная история
      - name: 'Сохранение изменений в репозиторий'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 Авто-обновление: плейлист синхронизирован'
          file_pattern: 'IPTV_SHARED.m3u'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'
